@startuml

class Dinosauro
class Obstaculo
class Personaje
class Ave
class Escenario
class Puntuacion


Juego *- Dinosauro
Juego *- Escenario
Escenario *- Obstaculo
Dinosauro *- Puntuación

Ave -|> Obstaculo
Dinosauro -|> Personaje

Dinosaurio o- Obstaculo


@enduml